const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';
const CHANGE_CAT_FILTER = 'CHANGE_CAT_FILTER'

export { FETCH_MENU_REQUEST, FETCH_MENU_SUCCESS, FETCH_MENU_FAILURE, CHANGE_CAT_FILTER };
