const FETCH_RECIPE = 'FETCH_RECIPE';
const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE';

export { FETCH_RECIPE, FETCH_RECIPE_SUCCESS, FETCH_RECIPE_FAILURE };
